# Q5 Which biological sources are asserted as FACT? Must be empty: taxa live only in propositions.
PREFIX codhmo: <https://codicum.eu/ontology/codhmo#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX crmsci: <http://www.cidoc-crm.org/extensions/crmsci/>
PREFIX crminf: <http://www.cidoc-crm.org/extensions/crminf/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?material ?taxon WHERE { ?material codhmo:hasBiologicalSource ?taxon . }
