"""Convert the Granzotti et al. 2026 (PXD056094) supplements into CODHMO Turtle.

Generalises examples/granzotti-2026-mm13944-s1-ground-layer.ttl, which was mapped by hand
first, to every claim row in both supplement tables (handover step 4.4).

The three normalisation tables in data/granzotti-2026/ are the only place where source
strings are interpreted. Nothing here hard-codes a taxon, an institution or a tier:
if a source string is not in a table, conversion STOPS rather than guessing.

The source TSVs are transcriptions of a published supplement and are never edited;
every defect is repaired on join.

Usage:
    python tools/granzotti_to_codhmo.py --out data/granzotti-2026/granzotti-2026.ttl
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "granzotti-2026"
# The supplements live in the library repo, beside the paper.
SUPP = ROOT.parent / "Palaeoprot-Publications" / "library" / "heritage_science" / "glues"

S1_NAME = "Granzotti et al. 2026 Table S1 - proteins identified.tsv"
S2_NAME = "Granzotti et al. 2026 Table S2 - taxonomic specific peptides.tsv"
DOI = "https://doi.org/10.1126/sciadv.ady3618"

PREFIXES = """# GENERATED by tools/granzotti_to_codhmo.py -- do not edit by hand.
# Source: Granzotti et al. 2026, doi:10.1126/sciadv.ady3618 (PXD056094), tables S1 and S2.
# Curated counterpart: examples/granzotti-2026-mm13944-s1-ground-layer.ttl (mapped by hand).
#
# Measurements (MQ score, mass, retention, spectrum counts) are deliberately absent: a taxon
# attribution is interpretation and belongs here; an eluting peptide does not.

@prefix codhmo: <https://codicum.eu/ontology/codhmo#> .
@prefix crm:    <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix crmsci: <http://www.cidoc-crm.org/extensions/crmsci/> .
@prefix crminf: <http://www.cidoc-crm.org/extensions/crminf/> .
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix ncbi:   <http://purl.obolibrary.org/obo/NCBITaxon_> .
@prefix g:      <https://codicum.eu/data/granzotti-2026/> .
"""


# --- normalisation tables --------------------------------------------------

def _read_table(path: Path) -> list[dict]:
    rows, header = [], None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line.strip():
            continue
        parts = line.split("\t")
        if header is None:
            header = parts
            continue
        rows.append(dict(zip(header, parts)))
    return rows


def load_tables():
    taxa = {r["source_string"]: r for r in _read_table(DATA / "taxon_normalisation.tsv")}
    inst = {r["source_string"]: r["canonical_name"]
            for r in _read_table(DATA / "institution_normalisation.tsv")}
    return taxa, inst


# --- the Blast ID / Taxonomy source grammar --------------------------------
# Parse order fixed by data/granzotti-2026/determinacy_normalisation.tsv:
#   1. parenthesis boundary (the comma before "(" is optional)
#   2. comma split
#   3. hybrid " x " per member (a hybrid can be ONE member of a comma list)
#   4. slash members -> their shared parent, via the taxon table
#
# Returns [(source_string, determinacy)], or [] when the source determined nothing.

COMPAT = re.compile(r"^Undetermine[d]*, compatible ", re.I)


def parse_taxonomy(cell: str) -> list[tuple[str, str]]:
    cell = cell.strip()
    if not cell:
        return []
    compat = bool(COMPAT.match(cell))
    cell = COMPAT.sub("", cell)
    if cell.strip() == "Undetermined":
        return []  # no attribution -> NO hypothesis is emitted at all

    # 1. split on the paren boundary, keeping which side each part came from
    preferred, alternatives = [], []
    depth, buf, cur = 0, "", preferred
    for ch in cell:
        if ch == "(":
            preferred.append(buf); buf, cur, depth = "", alternatives, depth + 1
        elif ch == ")":
            cur.append(buf); buf, cur, depth = "", preferred, depth - 1
        else:
            buf += ch
    cur.append(buf)

    def members(chunks):
        out = []
        for chunk in chunks:
            for m in chunk.split(","):           # 2. comma
                m = m.strip().rstrip(",").strip()
                if m:
                    out.append(m)                # 3./4. handled by table lookup
        return out

    pref, alts = members(preferred), members(alternatives)

    if compat:
        return [(m, "compatible-only") for m in pref + alts]
    if not pref:
        # fully parenthesised: a candidate set with no preferred member
        return [(m, "alternatives-only") for m in alts]
    return ([(m, "determined") for m in pref]
            + [(m, "alternatives-only") for m in alts])


# --- IRI helpers -----------------------------------------------------------

def slug(*parts) -> str:
    s = "-".join(str(p) for p in parts)
    s = re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-")
    return s or "x"


def lit(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# --- conversion ------------------------------------------------------------

def convert(strict: bool = True) -> tuple[str, dict]:
    taxa, inst = load_tables()
    out, stats = [PREFIXES], {
        "rows": 0, "samples": 0, "objects": 0, "hypotheses": 0,
        "undetermined_rows": 0, "unmapped": set(), "unmapped_inst": set(),
    }

    def rows_of(name, tax_col, label_col):
        with open(SUPP / name, encoding="utf-8") as fh:
            for i, r in enumerate(csv.reader(fh, delimiter="\t")):
                if i == 0 or len(r) < 7 or not r[0].strip():
                    continue
                yield [c.strip() for c in r], tax_col, label_col, name

    all_rows = list(rows_of(S1_NAME, 6, 5)) + list(rows_of(S2_NAME, 6, 4))

    samples, emitted_h = {}, set()
    body = []

    for r, tax_col, label_col, table in all_rows:
        stats["rows"] += 1
        raw_inst, obj, samp, desc = r[0], r[1], r[2], r[3]
        if raw_inst not in inst:
            stats["unmapped_inst"].add(raw_inst)
            continue
        institution = inst[raw_inst]
        key = (institution, obj, samp)
        samples.setdefault(key, desc or "sample")

        is_s2 = table == S2_NAME
        seq = r[5] if is_s2 else ""
        # protein name carries forward across continuation rows within a sample
        pname = r[label_col]
        if not pname:
            pname = samples.get(("_lastprot", key), "")
        samples[("_lastprot", key)] = pname

        oslug = slug(institution, obj, samp)
        row_id = slug(seq) if is_s2 else slug(pname)
        obs = f"g:obs-{oslug}-{row_id}"
        loc = f"g:loc-{oslug}-{row_id}"

        parsed = parse_taxonomy(r[tax_col])
        if not parsed:
            stats["undetermined_rows"] += 1

        # taxa -> hypotheses
        hyps, unknown = [], False
        for src, det in parsed:
            row = taxa.get(src)
            if row is None:
                stats["unmapped"].add(src); unknown = True; continue
            if row["defect"] == "shared-parent":
                det = "determined"
            hid = f"g:H-{oslug}-{row['taxid']}-{det}"
            hyps.append((hid, row, det))
        if unknown and strict:
            continue

        body.append(f"\n{obs} a crmsci:S4_Single_Observation ;")
        body.append(f'    rdfs:label {lit((pname or "protein") + ((" / " + seq) if seq else ""))}@en ;')
        body.append(f"    crmsci:O8_observed g:sample-{oslug} ;")
        body.append(f"    codhmo:hasDocumentLocator {loc} ;")
        rel = [f"codhmo:supports {h}" for h, _, d in hyps if d == "determined"]
        weak = [h for h, _, d in hyps if d != "determined"]
        if weak:
            rel.append("codhmo:compatibleWith " + " , ".join(weak))
        body.append("    " + " ;\n    ".join(rel) + " ." if rel else "    .")

        keys = [("Institution", raw_inst), ("Object Accession No.", obj), ("Sample No.", samp)]
        keys.append(("Sequence", seq) if is_s2 else ("Protein name", pname))
        body.append(f"{loc} a codhmo:DocumentLocator ;")
        body.append(f"    dcterms:source <{DOI}> ;")
        body.append(f"    codhmo:atTable {lit(table)} ;")
        body.append("    codhmo:hasKey " + " , ".join(f"{loc}-k{i}" for i in range(len(keys))) + " .")
        for i, (kn, kv) in enumerate(keys):
            body.append(f"{loc}-k{i} codhmo:keyName {lit(kn)} ; codhmo:keyValue {lit(kv)} .")

        for hid, row, det in hyps:
            if hid in emitted_h:
                continue
            emitted_h.add(hid); stats["hypotheses"] += 1
            note = f" [{row['note']}]" if row.get("note") else ""
            body.append(f"\n{hid} a codhmo:TaxonomicHypothesis ;")
            body.append(f'    rdfs:label {lit(row["current_label"] + " (" + row["rank"] + ")" + note)}@en ;')
            body.append(f"    crminf:J4_that {hid}-p ;")
            body.append(f"    crminf:J5_holds_to_be codhmo:{det} .")
            body.append(f"{hid}-p a crminf:I4_Proposition_Set ;")
            body.append(f"    rdf:subject g:layer-{oslug} ;")
            body.append("    rdf:predicate codhmo:hasBiologicalSource ;")
            body.append(f"    rdf:object ncbi:{row['taxid']} .")

        # competing: every determined hypothesis against every alternative of the same row
        det_h = [h for h, _, d in hyps if d == "determined"]
        alt_h = [h for h, _, d in hyps if d == "alternatives-only"]
        for a in det_h:
            for b in alt_h:
                body.append(f"{a} codhmo:hasCompetingHypothesis {b} .")
        for i, a in enumerate(alt_h):
            for b in alt_h[i + 1:]:
                body.append(f"{a} codhmo:hasCompetingHypothesis {b} .")

    # objects, layers, samples
    objs = {}
    for (institution, obj, samp), desc in [(k, v) for k, v in samples.items() if k[0] != "_lastprot"]:
        oslug = slug(institution, obj, samp)
        objs.setdefault((institution, obj), []).append((oslug, samp, desc))
        stats["samples"] += 1
    stats["objects"] = len(objs)

    head = []
    for (institution, obj), sl in sorted(objs.items()):
        oid = slug(institution, obj)
        head.append(f"\ng:object-{oid} a codhmo:HeritageObject ;")
        head.append(f'    rdfs:label {lit(obj + ", " + institution)}@en ;')
        head.append(f"    crm:P1_is_identified_by g:object-{oid}-id ;")
        head.append("    crm:P46_is_composed_of " + " , ".join(f"g:layer-{s}" for s, _, _ in sl) + " .")
        head.append(f"g:object-{oid}-id a crm:E42_Identifier ; crm:P190_has_symbolic_content {lit(obj)} .")
        for s, samp, desc in sl:
            head.append(f"g:layer-{s} a codhmo:MaterialLayer ; rdfs:label {lit(desc)}@en ;")
            head.append("    crm:P45_consists_of codhmo:collagen-adhesive .")
            head.append(f"g:sampling-{s} a crmsci:S2_Sample_Taking ;")
            head.append(f"    crmsci:O3_sampled_from g:layer-{s} ; crmsci:O4_sampled_at g:region-{s} ;")
            head.append(f"    crmsci:O5_removed g:sample-{s} ;")
            head.append("    crm:P14_carried_out_by g:granzotti-team ; crm:P4_has_time-span g:before-capture .")
            head.append(f'g:region-{s} a crm:E53_Place ; rdfs:label {lit("Sampling spot " + samp)}@en .')
            head.append(f"g:sample-{s} a crmsci:S13_Sample ; crmsci:O5i_was_removed_by g:sampling-{s} ;")
            head.append(f"    crm:P1_is_identified_by g:sample-{s}-id .")
            head.append(f"g:sample-{s}-id a crm:E42_Identifier ; "
                        f"crm:P190_has_symbolic_content {lit(obj + ' / ' + samp)} .")

    head.append('\ng:granzotti-team a crm:E74_Group ; rdfs:label "Granzotti et al. research team"@en ;')
    head.append(f"    dcterms:source <{DOI}> .")
    head.append("g:before-capture a crm:E52_Time-Span ;")
    head.append('    rdfs:comment "Sampling date not reported; bounded by the capture of the paper."@en ;')
    head.append('    crm:P82b_end_of_the_end "2026-09-18T00:00:00"^^xsd:dateTime .')

    out.extend(head); out.extend(body)
    return "\n".join(out) + "\n", stats


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(DATA / "granzotti-2026.ttl"))
    ap.add_argument("--lax", action="store_true",
                    help="emit rows with unmapped taxa instead of stopping (diagnostic only)")
    a = ap.parse_args()

    ttl, st = convert(strict=not a.lax)
    if st["unmapped"] or st["unmapped_inst"]:
        print("REFUSING: source strings absent from the normalisation tables.", file=sys.stderr)
        for s in sorted(st["unmapped"]):
            print("  taxon      :", s, file=sys.stderr)
        for s in sorted(st["unmapped_inst"]):
            print("  institution:", s, file=sys.stderr)
        return 1

    Path(a.out).write_text(ttl, encoding="utf-8")
    print(f"wrote {a.out}")
    print(f"  claim rows read     : {st['rows']}")
    print(f"  objects             : {st['objects']}")
    print(f"  samples             : {st['samples']}")
    print(f"  hypotheses          : {st['hypotheses']}")
    print(f"  rows with no taxon  : {st['undetermined_rows']} (correctly yield NO hypothesis)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
