"""Convert the Peters et al. 2025 megafauna deposit (Zenodo 14418148) into CODHMO Turtle.

Second ZooMS pilot, deliberately unlike the palimpsest: three fossil reference
specimens of extinct taxa whose identity is the PREMISE of the study (spectra were
taken to derive markers), not its conclusion. See data/peters-2025/../vinas-caron-2023/PILOT_FINDINGS.md.

Spectra stay in ZoomzPeak; keys mirror mzPeak (run = source file, spectrum native id).

Usage:
    python tools/peters_2025_to_codhmo.py
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "peters-2025" / "source"
DOI = "https://doi.org/10.3389/fmamm.2025.1564287"
STORE, TABLE = "ZoomzPeak", "ZOOMS_SPECTRA"

# Extraction route per specimen, from the deposit description.
EXTRACTION = {
    "MBS01": ("ultrafiltered gelatin previously extracted for radiocarbon dating", "codhmo:gelatin"),
    "SCP02": ("acid-soluble collagen extraction", "codhmo:bone"),
    "MCP02": ("acid-soluble collagen extraction", "codhmo:bone"),
}

PREFIXES = """# GENERATED by tools/peters_2025_to_codhmo.py -- do not edit by hand.
# Source: Peters et al. 2025, doi:10.3389/fmamm.2025.1564287; deposit doi:10.5281/zenodo.14418148.

@prefix codhmo: <https://codicum.eu/ontology/codhmo#> .
@prefix crm:    <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix crmsci: <http://www.cidoc-crm.org/extensions/crmsci/> .
@prefix crminf: <http://www.cidoc-crm.org/extensions/crminf/> .
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos:   <http://www.w3.org/2004/02/skos/core#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix ncbi:   <http://purl.obolibrary.org/obo/NCBITaxon_> .
@prefix v:      <https://codicum.eu/data/peters-2025/> .
"""


def read_tsv(name: str) -> list[dict]:
    with open(SRC / name, encoding="utf-8", newline="") as fh:
        return list(csv.DictReader((l for l in fh if not l.startswith("#")), delimiter="\t"))


def lit(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').strip() + '"'


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-")


def convert() -> tuple[str, dict]:
    meta = read_tsv("metadata_zenodo.tsv")
    taxa = {r["species"]: r for r in read_tsv("taxon_normalisation.tsv")}
    spectra = defaultdict(list)
    for r in read_tsv("zoomzpeak_rows.tsv"):
        # file_id separators are inconsistent in the deposit ("MCP02_" and "MCP02-").
        spectra[re.split(r"[_-]", r["file_id"], maxsplit=1)[0]].append(r)

    missing = {r["Species"] for r in meta} - taxa.keys()
    if missing:
        sys.exit(f"species not in taxon_normalisation.tsv: {sorted(missing)}")

    out = [PREFIXES, f"""v:team a crm:E74_Group ; rdfs:label "Peters et al. research team"@en ; dcterms:source <{DOI}> .
v:before-publication a crm:E52_Time-Span ;
    rdfs:comment "Sampling date not reported; bounded by publication (June 2025)."@en ;
    crm:P82b_end_of_the_end "2025-06-03T23:59:59"^^xsd:dateTime .
"""]
    stats = defaultdict(int)
    for r in meta:
        code, species = r["Sample code"], r["Species"]
        tx = taxa[species]
        how, material = EXTRACTION[code]
        k = slug(code)
        out.append(f"""v:specimen-{k} a codhmo:HeritageObject ;
    rdfs:label {lit(f"{species} ({r['Common name']}) fossil specimen {code}")}@en ;
    crm:P1_is_identified_by v:specimen-{k}-id ; crm:P46_is_composed_of v:tissue-{k} .
v:specimen-{k}-id a crm:E42_Identifier ; crm:P190_has_symbolic_content {lit(code)} .
v:tissue-{k} a codhmo:MaterialLayer ; rdfs:label {lit(f"Collagen source of {code}")}@en ;
    crm:P45_consists_of {material} .
v:sampling-{k} a crmsci:S2_Sample_Taking ; rdfs:comment {lit(how)}@en ;
    crmsci:O3_sampled_from v:tissue-{k} ; crmsci:O5_removed v:sample-{k} ;
    crm:P14_carried_out_by v:team ; crm:P4_has_time-span v:before-publication .
v:sample-{k} a crmsci:S13_Sample ; crmsci:O5i_was_removed_by v:sampling-{k} ;
    crm:P1_is_identified_by v:sample-{k}-id .
v:sample-{k}-id a crm:E42_Identifier ; crm:P190_has_symbolic_content {lit(code)} .
""")
        obs = []
        for sp in sorted(spectra[code], key=lambda x: x["file_id"]):
            o = f"v:obs-{slug(sp['file_id'])}"
            obs.append(o)
            stats["spectrum_observations"] += 1
            # Keys: dataset_id + file_id are CODHMO-required; native_id is the mzML/mzPeak spectrum id
            # (held in ZoomzPeak's sample_id column, finding Z5).
            out.append(f"""{o} a crmsci:S4_Single_Observation ; rdfs:label {lit(f"ZooMS reference spectrum {sp['file_id']}")}@en ;
    crmsci:O8_observed v:sample-{k} ; codhmo:hasSourceRecord {o}-rec .
{o}-rec a codhmo:SourceRecord ;
    codhmo:inStore "{STORE}" ; codhmo:inTable "{TABLE}" ; codhmo:storeSchemaVersion {lit(sp['schema_version'])} ;
    dcterms:source <https://doi.org/10.5281/zenodo.14418148> ;
    codhmo:hasKey {o}-rec-k0 , {o}-rec-k1 , {o}-rec-k2 , {o}-rec-k3 .
{o}-rec-k0 codhmo:keyName "dataset_id" ; codhmo:keyValue {lit(sp['dataset_id'])} .
{o}-rec-k1 codhmo:keyName "file_id" ; codhmo:keyValue {lit(sp['file_id'])} .
{o}-rec-k2 codhmo:keyName "id" ; codhmo:keyValue {lit(sp['sample_id'])} .
{o}-rec-k3 codhmo:keyName "run" ; codhmo:keyValue {lit(sp['file_id'].rsplit('.', 1)[0])} .
""")
        # D28: the specimen's taxon is the study's premise, recorded as a CRM type assignment, not a hypothesis.
        # D29: GBIF when NCBI lacks the taxon, with the nearest NCBI ancestor.
        if tx["authority"] == "gbif":
            taxon = f"<https://www.gbif.org/species/{tx['taxon_id']}>"
            nearest = f" ;\n    codhmo:nearestNcbiTaxon ncbi:{tx['nearest_ncbi']}"
        else:
            taxon, nearest = f"ncbi:{tx['taxon_id']}", ""
        stats["type_assignments"] += 1
        stats[f"{tx['authority']}_{tx['rank']}"] += 1
        out.append(f"""v:typing-{k} a crm:E17_Type_Assignment ;
    rdfs:label {lit(f"{code} identified as {species} (reference specimen)")}@en ;
    crm:P41_classified v:tissue-{k} ; crm:P42_assigned {taxon}{nearest} ;
    crm:P14_carried_out_by v:team ; dcterms:source <{DOI}> .
""")
    stats["specimens"] = len(meta)
    return "\n".join(out), dict(stats)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=ROOT / "data" / "peters-2025" / "peters-2025.ttl")
    a = ap.parse_args()
    ttl, stats = convert()
    a.out.write_text(ttl, encoding="utf-8")
    print(a.out.relative_to(ROOT), stats)


if __name__ == "__main__":
    main()
