"""Convert the Viñas-Caron et al. 2023 palimpsest deposit (Zenodo 6967158) into CODHMO Turtle.

Pilot for ZooMS deposits: the spectra already sit in ZoomzPeak (ZOOMS_SPECTRA,
dataset_id=Caron_2023_Palimpsest); this graph holds only the interpretation and
points each observation at its spectrum row through a codhmo:SourceRecord (D23).

Samples with no deposited spectrum fall back to a codhmo:DocumentLocator on the
Dataset S1 row, as the Granzotti converter does for supplement tables.

A ZooMS call not in TAXA stops conversion rather than guessing.

Usage:
    python tools/zooms_deposit_to_codhmo.py --out data/vinas-caron-2023/vinas-caron-2023.ttl
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "vinas-caron-2023" / "source"
DOI = "https://doi.org/10.1016/j.isci.2023.106786"
DEPOSIT = "https://doi.org/10.5281/zenodo.6967158"
STORE, TABLE = "ZoomzPeak", "ZOOMS_SPECTRA"

# Source call -> [(taxid, label, determinacy)]. A multi-taxon call is a MIXTURE: one hypothesis per
# member linked by codhmo:compatibleWith (D15, D27); a member marked "?" is codhmo:tentative.
TAXA = {
    "Sheep": [("9940", "Ovis aries", "determined")],
    "Goat": [("9925", "Capra hircus", "determined")],
    "Sheep+Goat+Calf?": [("9940", "Ovis aries", "determined"), ("9925", "Capra hircus", "determined"),
                         ("9913", "Bos taurus", "tentative")],
}
METHOD = {"manual": "codhmo:method-manual-markers", "automated": "codhmo:method-automated-markers"}

PREFIXES = """# GENERATED by tools/zooms_deposit_to_codhmo.py -- do not edit by hand.
# Source: Viñas-Caron et al. 2023, doi:10.1016/j.isci.2023.106786; deposit doi:10.5281/zenodo.6967158.
# Spectra are NOT here: each observation points at a ZoomzPeak ZOOMS_SPECTRA row.

@prefix codhmo: <https://codicum.eu/ontology/codhmo#> .
@prefix crm:    <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix crmsci: <http://www.cidoc-crm.org/extensions/crmsci/> .
@prefix crminf: <http://www.cidoc-crm.org/extensions/crminf/> .
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix ncbi:   <http://purl.obolibrary.org/obo/NCBITaxon_> .
@prefix v:      <https://codicum.eu/data/vinas-caron-2023/> .
"""


def read_tsv(name: str) -> list[dict]:
    with open(SRC / name, encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def lit(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip() + '"'


def slug(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-")


def folio_label(row: dict) -> str:
    # dataset_S1 carries the folio number only; recto/verso comes from uoc_metadata.
    return f"f. {row['Sampled folio']}{row.get('side', '')}"


def convert() -> tuple[str, dict]:
    s1 = read_tsv("dataset_S1.tsv")
    side = {r["sample name"]: r["side"] for r in read_tsv("uoc_metadata.tsv")}
    spectra = defaultdict(list)
    schema = set()
    for r in read_tsv("zoomzpeak_rows.tsv"):
        spectra[r["sample_id"].rsplit("_", 1)[0]].append(r)
        schema.add(r["schema_version"])
    if len(schema) != 1:
        sys.exit(f"expected one ZoomzPeak schema version, got {sorted(schema)}")
    schema_version = schema.pop()

    unmapped = {r[c] for r in s1 for c in ("ZooMS ID (manual)", "ZooMS ID (automated)")} - TAXA.keys()
    if unmapped:
        sys.exit(f"unmapped ZooMS calls: {sorted(unmapped)}")

    out = [PREFIXES]
    out.append(f"""v:am-795-4to a codhmo:HeritageObject ;
    rdfs:label "AM 795 4to, Arnamagnæan Institute, Copenhagen"@en ;
    crm:P1_is_identified_by v:am-795-4to-id ;
    crm:P46_is_composed_of {' , '.join(sorted({f'v:leaf-f{r["Sampled folio"]}' for r in s1}))} .
v:am-795-4to-id a crm:E42_Identifier ; crm:P190_has_symbolic_content "AM 795 4to" .
v:team a crm:E74_Group ; rdfs:label "Viñas-Caron et al. research team"@en ; dcterms:source <{DOI}> .
v:before-publication a crm:E52_Time-Span ;
    rdfs:comment "Sampling date not reported; bounded by publication (iScience, June 2023)."@en ;
    crm:P82b_end_of_the_end "2023-06-30T23:59:59"^^xsd:dateTime .
""")
    stats = defaultdict(int)
    leaves = set()
    for r in s1:
        lab = r["Lab name"]
        k = slug(lab)
        r["side"] = side.get(lab, "")
        fol = folio_label(r)
        leaf = f"v:leaf-f{r['Sampled folio']}"
        if leaf not in leaves:  # D32: one layer per leaf; folio 89 is sampled twice
            leaves.add(leaf)
            out.append(f"""{leaf} a codhmo:MaterialLayer ; rdfs:label {lit(f"Parchment of f. {r['Sampled folio']} (quire {r['Quire']})")}@en ;
    crm:P45_consists_of codhmo:parchment .
""")
        out.append(f"""v:sampling-{k} a crmsci:S2_Sample_Taking ;
    crmsci:O3_sampled_from {leaf} ; crmsci:O4_sampled_at v:region-{k} ; crmsci:O5_removed v:sample-{k} ;
    crm:P14_carried_out_by v:team ; crm:P4_has_time-span v:before-publication .
v:region-{k} a crm:E53_Place ; rdfs:label {lit(f"Eraser rubbing, {fol}")}@en .
v:sample-{k} a crmsci:S13_Sample ; crmsci:O5i_was_removed_by v:sampling-{k} ;
    crm:P1_is_identified_by v:sample-{k}-id .
v:sample-{k}-id a crm:E42_Identifier ; crm:P190_has_symbolic_content {lit(lab)} .
""")
        # Observations: one per deposited replicate spectrum, else one on the S1 row.
        obs = []
        for sp in sorted(spectra.get(lab, []), key=lambda x: x["file_id"]):
            o = f"v:obs-{slug(sp['file_id'])}"
            obs.append(o)
            stats["spectrum_observations"] += 1
            out.append(f"""{o} a crmsci:S4_Single_Observation ; rdfs:label {lit(f"ZooMS spectrum {sp['file_id']}")}@en ;
    crmsci:O8_observed v:sample-{k} ; codhmo:hasSourceRecord {o}-rec .
{o}-rec a codhmo:SourceRecord ;
    codhmo:inStore "{STORE}" ; codhmo:inTable "{TABLE}" ; codhmo:storeSchemaVersion {lit(schema_version)} ;
    dcterms:source <{DEPOSIT}> ;
    codhmo:hasKey {o}-rec-k0 , {o}-rec-k1 , {o}-rec-k2 .
{o}-rec-k0 codhmo:keyName "dataset_id" ; codhmo:keyValue {lit(sp['dataset_id'])} .
{o}-rec-k1 codhmo:keyName "run" ; codhmo:keyValue {lit(sp['file_id'].rsplit('.', 1)[0])} .
{o}-rec-k2 codhmo:keyName "file_id" ; codhmo:keyValue {lit(sp['file_id'])} .
""")
        if not obs:
            o = f"v:obs-{k}-s1"
            obs.append(o)
            stats["samples_without_spectra"] += 1
            out.append(f"""{o} a crmsci:S4_Single_Observation ; rdfs:label {lit(f"ZooMS result for {lab} (no deposited spectrum)")}@en ;
    crmsci:O8_observed v:sample-{k} ; codhmo:hasDocumentLocator {o}-loc .
{o}-loc a codhmo:DocumentLocator ; dcterms:source <{DEPOSIT}> ; codhmo:atTable "Dataset S1" ;
    codhmo:hasKey {o}-loc-k0 .
{o}-loc-k0 codhmo:keyName "Lab name" ; codhmo:keyValue {lit(lab)} .
""")

        # Hypotheses: the manual call is the paper's; the automated call is kept only where it differs.
        calls = [("manual", r["ZooMS ID (manual)"])]
        if r["ZooMS ID (automated)"] != r["ZooMS ID (manual)"]:
            calls.append(("automated", r["ZooMS ID (automated)"]))
            stats["manual_vs_automated_conflicts"] += 1
        hyp_ids = []
        for method, call in calls:
            taxa = TAXA[call]
            members = [f"v:H-{k}-{method}-{t}" for t, _, _ in taxa]
            for taxid, name, determinacy in taxa:
                det = f"codhmo:{determinacy}"
                h = f"v:H-{k}-{method}-{taxid}"
                hyp_ids.append(h)
                stats["hypotheses"] += 1
                out.append(f"""{h} a codhmo:TaxonomicHypothesis ;
    rdfs:label {lit(f"{fol} parchment is {name} ({method} ZooMS call '{call}')")}@en ;
    crminf:J4_that {h}-p ; crminf:J5_holds_to_be {det} .
{h}-p a crminf:I4_Proposition_Set ;
    rdf:subject {leaf} ; rdf:predicate codhmo:hasBiologicalSource ; rdf:object ncbi:{taxid} .
v:inference-{k}-{method}-{taxid} a crminf:I5_Inference_Making ;
    rdfs:label {lit(f"{method} ZooMS assignment for {lab}")}@en ; dcterms:source <{DOI}> ;
    crm:P33_used_specific_technique {METHOD[method]} ;
    crminf:J1_used_as_premise {' , '.join(obs)} ;
    crminf:J2_concluded_that {h} .
""")
                if len(members) > 1:  # mixture members co-occur (D15), never compete
                    out.append(f"{h} codhmo:compatibleWith {' , '.join(m for m in members if m != h)} .\n")
            for o in obs:
                out.append(f"{o} codhmo:supports {' , '.join(members)} .\n")
        if len(calls) > 1:
            man = [h for h in hyp_ids if "-manual-" in h]
            aut = [h for h in hyp_ids if "-automated-" in h]
            for a in aut:
                for m in man:
                    if a.rsplit("-", 1)[1] != m.rsplit("-", 1)[1]:
                        out.append(f"{a} codhmo:hasCompetingHypothesis {m} .\n")
    stats["samples"] = len(s1)
    return "\n".join(out), dict(stats)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=ROOT / "data" / "vinas-caron-2023" / "vinas-caron-2023.ttl")
    a = ap.parse_args()
    ttl, stats = convert()
    a.out.write_text(ttl, encoding="utf-8")
    print(a.out.relative_to(ROOT), stats)


if __name__ == "__main__":
    main()
